### ISSUE TITLE
Getting ready for launch: Umbrella issue

### ISSUE THREAD

**Issue by rogermparent** [iterative/cml.dev#1]
This issue is meant to be a hub for discussion about pre-launch preparations for the cml.dev website. This issue should close just before the site goes public.

Sorted roughly in order of priority:

- [x] Highlighted text (tooltips part 1) #2 #3
- [x] Add final examples with tooltips in the right places (I think? may or may not remove cloud case)
- [x] SEO Part 1: Metadata and good Lighthouse scores #15 
- [x] SEO part 2: Small details and keyword analysis #17 
- [x] Make the final landing videos #9 
- [x] Improve the container element for the landing video #4 
- [x] Background image #10 
- [x] Add the DVC.org logo to the footer
- [x] Add an action to the subscribe form #14 
- [x] Ensure we have the social icons we want #13 
- [x] Refine styles/sizes to be DRYer and fully match the Figma (Very close, working toward 100% if not there already)
- [x] Tooltips on highlights #2 #3 (Feature complete, but may need design adjustments)
- [x] Make a Readme for site contributors (A skeleton, currently)

Individual issues will be created and linked here. This umbrella issue is probably best used for discussion around discovering and adding new pre-release issues.
