### ISSUE TITLE
ref: screenshots

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#209]
add screenshots of:

- [ ] `send-comment` effect of options `--pr` and `--update`
- [ ] `pr` effect of option `--auto-merge` (related #153)
- [ ] `send-github-check`
- [ ] `tensorboard-dev`
