### ISSUE TITLE
Bitbucket runner release

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#258]
- [x] Example repositories (tracked on https://github.com/iterative/example-repos-dev/issues/100)
  + [x] https://bitbucket.org/iterative-ai/example-cml
  + [x] https://bitbucket.org/iterative-ai/cml-base-case
  + [x] https://bitbucket.org/iterative-ai/cml-cloud-case
- [x] Getting started guide (https://github.com/iterative/cml.dev/pull/257)
- [ ] Toggle switch on the cml.dev landing page
- [ ] blog
