### ISSUE TITLE
add Bitbucket to home page

### ISSUE THREAD

**Issue by casperdcl** [iterative/cml.dev#349]
https://cml.dev/ "CML Use Cases" only has GH & GL (missing BB) runners.

- [ ] add Bitbucket tab to https://github.com/iterative/cml.dev/blob/master/src/components/pages/Home/UseCasesSection/index.tsx
  + [ ] sort out demo repos https://github.com/iterative/cml-examples-dev/issues/9
    + [x] basic demo repo (https://bitbucket.org/iterative-ai/cml-base-case, also used in https://cml.dev/doc/usage?tab=Bitbucket)
    + [ ] DVC demo repo (https://bitbucket.org/iterative-ai/cml-example-dvc?)
      * [ ] use in home page #362
      * [ ] also use in new tab in https://github.com/iterative/cml.dev/blob/master/content/docs/cml-with-dvc.md
    + [ ] Tensorboard demo repo (https://bitbucket.org/iterative-ai/cml-example-tensorboard?)
    + [ ] Runner demo repo (https://bitbucket.org/iterative-ai/cml-cloud-case?)
    + [ ] Runner GPU demo repo (use TPI directly https://github.com/iterative/cml.dev/issues/367?)
- [ ] add to Bitbucket "example projects" section https://github.com/iterative/cml.dev/blob/master/content/docs/usage.md

**Comment by jorgeorpinel** [comment]
Just a couple relatively off-topic notes wrt terminology (sorry, it may be annoying but I think we also want to make sure we're talking the same language):

- I call cml.dev/ the _home page_. To me [landing pages](https://mailchimp.com/marketing-glossary/landing-pages/) are other pages intended to capture new traffic for the site (e.g. use case pages in dvc.org/doc, which brings me to...)

- The "[Use Cases](https://cml.dev/#use-cases)" here are a bit low-level. I would not really call these "use cases".

  > Going with [Wikipedia](https://en.wikipedia.org/wiki/Use_case) on this one 😋: "situations where a piece of software may be useful"; to me this means very general, high-level situations. It may well be that there's a single one e.g. _CML let's you do ML on CI/CD_.

**Comment by casperdcl** [comment]
hmm, levels to me:

- highest-level: features (currently should be on "home" pages but often neglected)
- high-level: scenarios/problems
- mid-level: use cases
- low-level: user guide
- lowest-level: cmd ref

worth discussing, wonder if worth cross-posting somewhere else (*cough* https://github.com/iterative/dvc.org/issues/144)

**Comment by jorgeorpinel** [comment]
> high-level: scenarios/problems

That's what I mean by use case. Happy to change our official terminology if we can get more people to agree.

> mid-level: use cases

Yes there's also the more technical use of the term "use case" (as in [UML diagrams](https://en.wikipedia.org/wiki/Use_case_diagram)), if that's what you're thinking.

**Comment by jorgeorpinel** [comment]
> wonder if worth cross-posting somewhere else

https://www.notion.so/iterative/Framework-7e86e484e50e42529df3dbfe32b4e987#cc1d6d4ea1c2408d9892d7954aa98b12 🙂 (not a great place for discussions though).

**Comment by 0x2b3bfa0** [comment]
Worth mentioning https://github.com/iterative/cml-examples-dev

**Comment by DavidGOrtega** [comment]
> Worth mentioning https://github.com/iterative/cml-examples-dev

Indeed I have a question. Do I have to create the repos? It's not that repo generating that for us? @0x2b3bfa0

**Comment by 0x2b3bfa0** [comment]
No, you don't have to do anything. The [cml-examples-dev](https://github.com/iterative/cml-examples-dev) generator is in charge of both creating and provisioning the repositories.

**Comment by DavidGOrtega** [comment]
Ok so according to this I should just make a PR a slightly alter the yaml in BB

**Comment by 0x2b3bfa0** [comment]
Yes, please open pull requests with whatever changes you want and grab the repository links from the table in the README.

**Comment by casperdcl** [comment]
@0x2b3bfa0 are you going to push https://bitbucket.com/iterative-test to https://bitbucket.com/iterative-ai? Specifically these:

- https://bitbucket.org/iterative-test/cml-example-dvc
- https://bitbucket.org/iterative-test/cml-example-tensorboard

(currently blocking #362)

**Comment by 0x2b3bfa0** [comment]
> _@0x2b3bfa0 are you going to push https://bitbucket.com/iterative-test to https://bitbucket.com/iterative-ai?_

Do I have the choice? 😂
